# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubantu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install and build'
- bash: |
    npm install -g appium
    brew install --cask android-sdk
  displayName: 'Install appium'
- task: CmdLine@2
  inputs:
    script: |
      #!/usr/bin/env bash
      env
      echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install 'system-images;android-25;google_apis;x86'
      $ANDROID_HOME/platform-tools/adb devices
      adb devices | grep "emulator-" | while read -r emulator device; do adb -s $emulator emu kill; done
      adb kill-server
      $ANDROID_HOME/tools/bin/avdmanager delete avd -n Nexus 5 API 30
      $ANDROID_HOME/platform-tools/adb devices
      echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd -n Nexus 5 API 30 -k 'system-images;android-25;google_apis;x86' --force
      nohup $ANDROID_HOME/emulator/emulator -memory 2500 -avd Nexus 5 API 30 -skin 768x1280 -no-snapshot > /dev/null 2>&1 & $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
      echo "Emulator started"
    failOnStderr: true
  displayName: 'Emulator setup'
- script: |
    npm run testandroidbrowser
  continueOnError: true
  displayName: 'Run android mobile tests'
